# Generated by Django 2.0.4 on 2018-05-19 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_auto_20180519_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='birthday',
            field=models.DateField(default='0000-00-00'),
        ),
    ]
